### ISSUE TITLE
#PDFsMatter! 

### ISSUE THREAD

**Issue by SinaB0ck** [OCR4all/getting_started#16]
Have read the manual, partly maybe not up to date? PDFs can't seem to be ocred at the moment?

**Comment by maxnth** [comment]
Not sure what this issue is exactly about but as noted in the README the documentation / getting started guide has been fully moved to [ocr4all.org](https://www.ocr4all.org/), PDFs are no longer offered by us and were already removed from this repository (see 623c7e3) to avoid any confusion.

In case this is a question about whether it's possible to OCR PDFs with OCR4all:
The currently available version of OCR4all accepts using PDF files as input but the result will be PAGE XML / TXT files. Embedding the ocr results as text into PDFs is currently not possible.
