### ISSUE TITLE
Cloud setup instruction

### ISSUE THREAD

**Issue by svetlinsem** [OCR4all/getting_started#6]
Hello Team,

your project is great and if i manage to install it ill be great. I want to ask if there is an opportunity to make instructions on how to install in Google Cloud, AWS.
Thanks in advance.

**Comment by maxnth** [comment]
Releasing extensive instructions for setting up OCR4all in a specific cloud environment sadly isn't a feasible option for us at the moment because of the wide array of cloud computing providers and different instances every one of these providers offers. 
We will keep this request in mind though.

Using any of the available tutorials/documentations for setting up a Docker container on [AWS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html), [Azure](https://docs.microsoft.com/de-de/azure/container-instances/container-instances-quickstart), etc. should work with our OCR4all Docker image as well. This consistency across platforms is one of the advantages of the Docker ecosystem. 

If there are any problems related to OCR4all and/or its Docker image itself we'd be happy to assist you.
