### ISSUE TITLE
Import text structure (LAREX)

### ISSUE THREAD

**Issue by jpb-badw** [OCR4all/getting_started#9]
I’ve done a preconfiguration test run with a single page of a book. I’ve configured the regions and reading orders. How do I export and import this configuration to apply it to the whole book?

**Comment by maxnth** [comment]
We just added a batch processing mode in release 0.5.0 of OCR4all/LAREX so that might be what you're looking for.
Regarding importing/exporting settings LAREX sadly doesn't offer support for **all** settings at the moment but we're aware of this problem and will most likely fix this in the next release.
